#include "../Inc/display.h"

void enable0(){
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_6,RESET);
};
void enable1(){
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7,RESET);
};
void disable0(){
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_6,SET);
};
void disable1(){
	HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7,SET);
};
void display7SEG(int number) {
	switch(number){
		case 0:
				HAL_GPIO_WritePin(GPIOB,GPIO_PIN_0,RESET); //g
				HAL_GPIO_WritePin(GPIOB,GPIO_PIN_1,RESET); //f
				HAL_GPIO_WritePin(GPIOB,GPIO_PIN_2,RESET);//e
				HAL_GPIO_WritePin(GPIOB,GPIO_PIN_3,RESET);//d
				HAL_GPIO_WritePin(GPIOB,GPIO_PIN_4,RESET); //c
				HAL_GPIO_WritePin(GPIOB,GPIO_PIN_5,RESET); //b
				HAL_GPIO_WritePin(GPIOB,GPIO_PIN_6,SET); //a
				break;
		case 1:
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_0,SET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_1,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_2,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_3,SET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_4,SET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_5,SET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_6,SET);
				break;
		case 2:
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_0,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_1,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_2,SET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_3,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_4,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_5,SET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_6,RESET);
				break;
		case 3:
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_0,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_1,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_2,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_3,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_4,SET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_5,SET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_6,RESET);
				break;
		case 4:
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_0,SET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_1,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_2,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_3,SET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_4,SET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_5,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_6,RESET);
				break;
		case 5:
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_0,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_1,SET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_2,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_3,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_4,SET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_5,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_6,RESET);
				break;
		case 6:
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_0,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_1,SET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_2,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_3,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_4,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_5,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_6,RESET);
			break;
		case 7:
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_0,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_1,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_2,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_3,SET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_4,SET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_5,SET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_6,SET);
				break;
		case 8:
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_0,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_1,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_2,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_3,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_4,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_5,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_6,RESET);
				break;
		case 9:
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_0,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_1,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_2,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_3,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_4,SET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_5,RESET);
			HAL_GPIO_WritePin(GPIOB,GPIO_PIN_6,RESET);
				break;
	}
}
;
