
#include "../Inc/exercise4.h"

void display7SEG_H(int number) {
	switch(number){
		case 0:
				HAL_GPIO_WritePin(GPIOA,GPIO_PIN_8,RESET); //g
				HAL_GPIO_WritePin(GPIOA,GPIO_PIN_9,RESET); //f
				HAL_GPIO_WritePin(GPIOA,GPIO_PIN_10,RESET);//e
				HAL_GPIO_WritePin(GPIOA,GPIO_PIN_11,RESET);//d
				HAL_GPIO_WritePin(GPIOA,GPIO_PIN_12,RESET); //c
				HAL_GPIO_WritePin(GPIOA,GPIO_PIN_13,RESET); //b
				HAL_GPIO_WritePin(GPIOA,GPIO_PIN_14,SET); //a
				break;
		case 1:
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_8,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_9,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_10,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_11,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_12,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_13,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_14,SET);
				break;
		case 2:
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_8,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_9,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_10,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_11,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_12,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_13,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_14,RESET);
				break;
		case 3:
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_8,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_9,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_10,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_11,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_12,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_13,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_14,RESET);
				break;
		case 4:
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_8,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_9,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_10,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_11,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_12,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_13,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_14,RESET);
				break;
		case 5:
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_8,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_9,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_10,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_11,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_12,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_13,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_14,RESET);
				break;
		case 6:
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_8,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_9,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_10,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_11,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_12,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_13,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_14,RESET);
			break;
		case 7:
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_8,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_9,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_10,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_11,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_12,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_13,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_14,SET);
				break;
		case 8:
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_8,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_9,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_10,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_11,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_12,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_13,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_14,RESET);
				break;
		case 9:
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_8,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_9,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_10,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_11,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_12,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_13,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_14,RESET);
				break;
	}
}
;
void display7SEG_V(int number) {
	switch(number){
		case 0:
				HAL_GPIO_WritePin(GPIOA,GPIO_PIN_1,RESET); //g
				HAL_GPIO_WritePin(GPIOA,GPIO_PIN_2,RESET); //f
				HAL_GPIO_WritePin(GPIOA,GPIO_PIN_3,RESET);//e
				HAL_GPIO_WritePin(GPIOA,GPIO_PIN_4,RESET);//d
				HAL_GPIO_WritePin(GPIOA,GPIO_PIN_5,RESET); //c
				HAL_GPIO_WritePin(GPIOA,GPIO_PIN_6,RESET); //b
				HAL_GPIO_WritePin(GPIOA,GPIO_PIN_7,SET); //a
				break;
		case 1:
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_1,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_2,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_3,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_4,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_5,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_6,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_7,SET);
				break;
		case 2:
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_1,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_2,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_3,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_4,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_5,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_6,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_7,RESET);
				break;
		case 3:
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_1,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_2,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_3,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_4,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_5,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_6,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_7,RESET);
				break;
		case 4:
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_1,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_2,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_3,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_4,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_5,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_6,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_7,RESET);
				break;
		case 5:
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_1,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_2,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_3,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_4,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_5,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_6,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_7,RESET);
				break;
		case 6:
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_1,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_2,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_3,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_4,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_5,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_6,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_7,RESET);
			break;
		case 7:
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_1,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_2,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_3,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_4,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_5,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_6,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_7,SET);
				break;
		case 8:
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_1,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_2,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_3,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_4,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_5,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_6,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_7,RESET);
				break;
		case 9:
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_1,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_2,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_3,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_4,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_5,SET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_6,RESET);
			HAL_GPIO_WritePin(GPIOA,GPIO_PIN_7,RESET);
				break;
	}
}
;
